Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-12, with the labels that each got.

#221 Added validations for conversion metrics
  .changes/unreleased/Features-20231127-150021.yaml
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/validations/test_metrics.py
Labels: cla:yes

#222 bump to 0.5.0a2
  pyproject.toml
Labels: cla:yes, Skip Changelog

#224 [Backport to 0.4.latest] Add support for conversion metrics
  .changes/unreleased/Features-20231127-124601.yaml
  .changes/unreleased/Features-20231127-150021.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/type_enums/__init__.py
  dbt_semantic_interfaces/type_enums/conversion_calculation_type.py
  dbt_semantic_interfaces/type_enums/metric_type.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/parsing/test_metric_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_metrics.py
Labels: cla:yes

#226 Release PR for 0.4.2
  pyproject.toml
Labels: Skip Changelog

#231 add tracking for github advanced security
  .github/atlas.yaml
Labels: cla:yes, Skip Changelog

#230 Add dependabot config for version updates
  .github/dependabot.yml
Labels: cla:yes, Skip Changelog
