Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-10, with the labels that each got.

#161 [BACKPORT 0.2.latest] Support for null value coalescing
  .changes/unreleased/Features-20230926-182305.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/metric.py
  tests/parsing/test_metric_parsing.py
Labels: cla:yes

#162 Backport: Add support for `Dimension(...).grain(...)` in where filter
  .changes/unreleased/Features-20230929-123932.yaml
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/errors.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_dimension.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_entity.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  dbt_semantic_interfaces/parsing/where_filter_parser.py
  dbt_semantic_interfaces/protocols/query_interface.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#163 bump to 0.2.1dev1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#164 Bump to version 0.2.1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#165 Migrate from JsonSchema 3 to JsonSchema 4 (#160)
  .changes/unreleased/Dependencies-20230927-234903.yaml
  dbt_semantic_interfaces/parsing/schemas.py
  pyproject.toml
Labels: cla:yes

#166 Bump to 0.2.2
  pyproject.toml
Labels: cla:yes, Skip Changelog

#158 Support `label` attribute
  .changes/unreleased/Features-20230926-173230.yaml
  dbt_semantic_interfaces/implementations/elements/dimension.py
  dbt_semantic_interfaces/implementations/elements/entity.py
  dbt_semantic_interfaces/implementations/elements/measure.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/dimension.py
  dbt_semantic_interfaces/protocols/entity.py
  dbt_semantic_interfaces/protocols/measure.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/validations/labels.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  pyproject.toml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/accounts_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/companies.yaml
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_saved_query_parsing.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_labels.py
Labels: enhancement, cla:yes, Protocol Spec Change

#168 Fixed error message for entity in filter spec and where clause
  .changes/unreleased/Under the Hood-20231006-100304.yaml
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
Labels: cla:yes

#167 Fixed error message for entity in filter spec and where clause
  .changes/unreleased/Under the Hood-20231006-100304.yaml
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
Labels: cla:yes

#169 Bump version to 0.3.0b1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#170 Throw exceptions on invalid entity names in filter and group by expressions
  .changes/unreleased/Fixes-20231009-211057.yaml
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#171 Allow specification of filters as either lists or strings
  .changes/unreleased/Features-20231009-210737.yaml
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/protocols/where_filter.py
  dbt_semantic_interfaces/test_utils.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/saved_query.py
  tests/implementations/where_filter/test_parse_calls.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_saved_query_parsing.py
  tests/parsing/test_where_filter_parsing.py
  tests/validations/test_metrics.py
  tests/validations/test_saved_query.py
Labels: cla:yes

#176 Optional Time Granularity for Time Dimensions in the Where Filter
  .changes/unreleased/Features-20231010-111707.yaml
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#177 Bump version to 0.3.0 for release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#179 Add maintainer github issue template
  .github/ISSUE_TEMPLATE/implementation-ticket.yml
Labels: cla:yes, Skip Changelog, House keeping

#183 Support for date_part for Dimension & TimeDimension
  .changes/unreleased/Features-20231024-171020.yaml
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_dimension.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_parser.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  dbt_semantic_interfaces/type_enums/date_part.py
  tests/parsing/test_where_filter_parsing.py
Labels: cla:yes

#184 Begin Validating Metric Names
  .changes/unreleased/Breaking Changes-20231023-103143.yaml
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes

#190 Add exports config to YAML spec for saved queries
  .changes/unreleased/Features-20231024-162842.yaml
  .github/workflows/ci-schema-consistency.yaml
  Makefile
  dbt_semantic_interfaces/implementations/export.py
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/export.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/type_enums/export_destination_type.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/saved_queries.yaml
  tests/parsing/test_saved_query_parsing.py
  tests/test_implements_satisfy_protocols.py
Labels: cla:yes

#185 Validate Saved Query Names
  .changes/unreleased/Features-20231023-102225.yaml
  dbt_semantic_interfaces/type_enums/__init__.py
  dbt_semantic_interfaces/type_enums/semantic_manifest_node_type.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes

#186 Rename `SavedQuery.group_bys` to `SavedQuery.group_by`
  .changes/unreleased/Fixes-20231025-173704.yaml
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/validations/saved_query.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/saved_queries.yaml
  tests/parsing/test_saved_query_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_saved_query.py
Labels: cla:yes

#196 Nest query params in saved query YAML
  .changes/unreleased/Fixes-20231026-113940.yaml
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/validations/saved_query.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/saved_queries.yaml
  tests/parsing/test_saved_query_parsing.py
  tests/validations/test_saved_query.py
Labels: cla:yes

#198 Bump version to 0.4.0
  pyproject.toml
Labels: cla:yes, Skip Changelog

#194 Add typing-extensions>=4.4 requirement
  .changes/unreleased/Dependencies-20231026-122748.yaml
  pyproject.toml
Labels: cla:yes, Backport 0.2.latest

#199 [Backport] Update typing-extensions to require versions ~=4.4 (#194)
  .changes/unreleased/Dependencies-20231026-122748.yaml
  .changes/unreleased/Dependencies-20231026-161207.yaml
  pyproject.toml
Labels: cla:yes

#201 Update DSI version to 0.2.3 for backport release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#202 Revert "Update DSI version to 0.2.3 for backport release"
  pyproject.toml
Labels: cla:yes, Skip Changelog

#203 Throw exceptions on invalid entity names in filter and group by expressions
  .changes/unreleased/Fixes-20231009-211057.yaml
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#204 Update version to 0.2.3 for patch release
  pyproject.toml
Labels: cla:yes, Skip Changelog
