Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-05, with the labels that each got.

#34 Adding a pytest PR workflow
  .changes/unreleased/Under the Hood-20230515-125335.yaml
  .github/workflows/ci-pytest.yaml
Labels: cla:yes

#33 Adding type enums
  .changes/unreleased/Under the Hood-20230515-124059.yaml
  dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/type_enums/aggregation_type.py
  dbt_semantic_interfaces/type_enums/dimension_type.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/parsing/test_semantic_model_parsing.py
  tests/validations/test_agg_time_dimension.py
  tests/validations/test_dimension_const.py
  tests/validations/test_element_const.py
  tests/validations/test_metrics.py
  tests/validations/test_semantic_models.py
Labels: cla:yes

#35 Adding measure protocol
  .changes/unreleased/Features-20230515-155013.yaml
  dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/protocols/measure.py
Labels: cla:yes, review

#37 Update .gitignore to ignore OS / IDE files
  .gitignore
Labels: cla:yes, Skip Changelog

#41 Create Dimension Protocol
  .changes/unreleased/Features-20230516-150352.yaml
  dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/objects/where_filter/filter_renderer.py
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/protocols/dimension.py
  dbt_semantic_interfaces/protocols/metadata.py
  dbt_semantic_interfaces/type_enums/__init__.py
  dbt_semantic_interfaces/type_enums/time_granularity.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_filter_renderer.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_dimension_const.py
  tests/validations/test_metrics.py
  tests/validations/test_semantic_models.py
Labels: cla:yes

#36 Adding entity protocol
  .changes/unreleased/Features-20230515-161320.yaml
  dbt_semantic_interfaces/objects/elements/entity.py
  dbt_semantic_interfaces/protocols/entity.py
  dbt_semantic_interfaces/type_enums/entity_type.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/semantic_models.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_entities.py
  tests/validations/test_metrics.py
Labels: cla:yes, review

#42 Updating Measure Protocol
  .changes/unreleased/Fixes-20230516-172635.yaml
  dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/protocols/measure.py
  tests/test_implements_satisfy_protocols.py
Labels: cla:yes

#40 Adding metric protocol
  .changes/unreleased/Features-20230516-112250.yaml
  dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/type_enums/metric_type.py
  tests/test_implements_satisfy_protocols.py
Labels: cla:yes

#44 Add SemanticManifest Protocol
  .changes/unreleased/Features-20230516-162909.yaml
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  tests/test_implements_satisfy_protocols.py
Labels: cla:yes

#52 update used gh actions ahead of node12 deprecation
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#62 Bump mypy to 0.942
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#59 Add protocol definitions of semantic layer objects (with cleaner history)
  .changes/unreleased/Features-20230515-161320.yaml
  .changes/unreleased/Features-20230516-100539.yaml
  .changes/unreleased/Features-20230516-112250.yaml
  .changes/unreleased/Features-20230516-150352.yaml
  .changes/unreleased/Features-20230516-162909.yaml
  .changes/unreleased/Fixes-20230516-172635.yaml
  .changes/unreleased/Fixes-20230516-175643.yaml
  dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/objects/elements/entity.py
  dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/objects/filters/call_parameter_sets.py
  dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/objects/semantic_model.py
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/protocols/dimension.py
  dbt_semantic_interfaces/protocols/entity.py
  dbt_semantic_interfaces/protocols/measure.py
  dbt_semantic_interfaces/protocols/metadata.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/type_enums/__init__.py
  dbt_semantic_interfaces/type_enums/entity_type.py
  dbt_semantic_interfaces/type_enums/metric_type.py
  dbt_semantic_interfaces/type_enums/time_granularity.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/objects/where_filter/test_parse_calls.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_dimension_const.py
  tests/validations/test_entities.py
  tests/validations/test_metrics.py
  tests/validations/test_semantic_models.py
Labels: cla:yes

#63 Bump version to 0.1.0.dev1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#29 Packaging PR - Getting dbt-semantic-interfaces ready for PyPi
  .changes/unreleased/Under the Hood-20230516-102858.yaml
  pyproject.toml
Labels: cla:yes

#64 Adding semantic manifest version
  .changes/unreleased/Features-20230517-103947.yaml
  dbt_semantic_interfaces/implementations/semantic_manifest.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  pyproject.toml
  tests/implementations/test_semantic_manifest.py
Labels: cla:yes

#65 Revert to using WhereFilter.call_parameter_sets
  dbt_semantic_interfaces/implementations/filters/call_parameter_sets.py
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes, Skip Changelog

#68 Rename test fixtures to use `semantic manifest` terminology
  .changes/unreleased/Under the Hood-20230523-125933.yaml
  tests/conftest.py
  tests/fixtures/semantic_manifest_fixtures.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/accounts_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/companies.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/id_verifications.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/listings_latest.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/lux_listing_mapping.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/revenue.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/user_sm_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/users_latest.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/views_source.yaml
  tests/transformations/test_configurable_transform_rules.py
  tests/validations/test_common_entities.py
  tests/validations/test_configurable_rules.py
  tests/validations/test_element_const.py
  tests/validations/test_entities.py
  tests/validations/test_reserved_keywords.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes

#69 Add Schema Consistency CI Check
  .github/workflows/ci-schema-consistency.yaml
  dbt_semantic_interfaces/parsing/explicit_schema.py
  dbt_semantic_interfaces/parsing/schemas/default_explicit_schema.json
Labels: cla:yes, Skip Changelog

#71 Update mypy to 1.3.0 and fix type issues
  .changes/unreleased/Under the Hood-20230525-103207.yaml
  .pre-commit-config.yaml
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/implementations/base.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/common_entities.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/element_const.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/non_empty.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  pyproject.toml
Labels: cla:yes

#72 Use Common Hatch Environment for Testing & Linting + Parallelize Tests
  .github/workflows/ci-pre-commit.yaml
  .github/workflows/ci-pytest.yaml
  .github/workflows/ci-schema-consistency.yaml
  Makefile
  pyproject.toml
Labels: cla:yes, Skip Changelog

#74 Change Definition Protocols to Use An Abstract Property
  dbt_semantic_interfaces/implementations/elements/dimension.py
  dbt_semantic_interfaces/implementations/elements/entity.py
  dbt_semantic_interfaces/implementations/elements/measure.py
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  dbt_semantic_interfaces/implementations/metadata.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/semantic_manifest.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/model_transformer.py
  dbt_semantic_interfaces/model_validator.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/protocols/dimension.py
  dbt_semantic_interfaces/protocols/entity.py
  dbt_semantic_interfaces/protocols/measure.py
  dbt_semantic_interfaces/protocols/metadata.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/protocols/where_filter.py
  dbt_semantic_interfaces/test_utils.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/transformations/names.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/transformations/transform_rule.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/common_entities.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/element_const.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/non_empty.py
  dbt_semantic_interfaces/validations/reserved_keywords.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/fixtures/semantic_manifest_fixtures.py
  tests/implementations/test_semantic_manifest.py
  tests/implementations/where_filter/test_parse_calls.py
  tests/parsing/test_metadata_parsing.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_model_deserialization.py
  tests/test_implements_satisfy_protocols.py
  tests/test_pretty_print.py
  tests/transformations/test_configurable_transform_rules.py
  tests/validations/test_agg_time_dimension.py
  tests/validations/test_common_entities.py
  tests/validations/test_configurable_rules.py
  tests/validations/test_dimension_const.py
  tests/validations/test_element_const.py
  tests/validations/test_entities.py
  tests/validations/test_metrics.py
  tests/validations/test_reserved_keywords.py
  tests/validations/test_semantic_models.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes, Skip Changelog

#75 Change Validations to be Generic
  dbt_semantic_interfaces/model_validator.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/common_entities.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/element_const.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/non_empty.py
  dbt_semantic_interfaces/validations/reserved_keywords.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/parsing/test_metric_parsing.py
  tests/validations/test_agg_time_dimension.py
  tests/validations/test_common_entities.py
  tests/validations/test_configurable_rules.py
  tests/validations/test_dimension_const.py
  tests/validations/test_element_const.py
  tests/validations/test_entities.py
  tests/validations/test_measures.py
  tests/validations/test_metrics.py
  tests/validations/test_reserved_keywords.py
  tests/validations/test_semantic_models.py
  tests/validations/test_unique_valid_name.py
  tests/validations/test_validator_helpers.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes, Skip Changelog

#76 Remove `--ignore-missing-imports` from Mypy and Add Pydantic Plugin
  .pre-commit-config.yaml
  dbt_semantic_interfaces/parsing/dir_to_model.py
  mypy.ini
  pyproject.toml
  tests/validations/test_dimension_const.py
  tests/validations/test_metrics.py
  tests/validations/test_validator_helpers.py
Labels: cla:yes, Skip Changelog

#77 Change Transforms to be Generic
  dbt_semantic_interfaces/model_transformer.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/transformations/names.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/transformations/pydantic_rule_set.py
  dbt_semantic_interfaces/transformations/rule_set.py
  dbt_semantic_interfaces/transformations/transform_rule.py
  tests/fixtures/semantic_manifest_fixtures.py
  tests/transformations/test_configurable_transform_rules.py
  tests/validations/test_measures.py
Labels: cla:yes, Skip Changelog

#78 Add Protocol Hints
  dbt_semantic_interfaces/implementations/semantic_manifest.py
  dbt_semantic_interfaces/model_transformer.py
  dbt_semantic_interfaces/protocols/protocol_hint.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/transformations/names.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/transformations/pydantic_rule_set.py
  pyproject.toml
Labels: cla:yes, Skip Changelog

#80 Rename MetricType.MEASURE_PROXY to MetricType.SIMPLE.
  .changes/unreleased/Breaking Changes-20230529-190627.yaml
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/parsing/schemas/default_explicit_schema.json
  dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/type_enums/metric_type.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/parsing/test_metadata_parsing.py
  tests/parsing/test_metric_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_dimension_const.py
  tests/validations/test_metrics.py
Labels: cla:yes

#79 Add Defaults for SemanticModel
  .changes/unreleased/Breaking Changes-20230529-190835.yaml
  dbt_semantic_interfaces/implementations/elements/dimension.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/parsing/schemas/default_explicit_schema.json
  dbt_semantic_interfaces/protocols/dimension.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/test_utils.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/semantic_models.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/accounts_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/id_verifications.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/listings_latest.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/revenue.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/user_sm_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/users_latest.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/views_source.yaml
  tests/parsing/test_semantic_model_parsing.py
  tests/validations/test_agg_time_dimension.py
  tests/validations/test_dimension_const.py
  tests/validations/test_measures.py
  tests/validations/test_metrics.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes

#81 Bump version to 0.1.0.dev2
  pyproject.toml
Labels: cla:yes, Skip Changelog

#82 Naming Clean Up
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/transformations/names.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/transformations/semantic_manifest_transformer.py
  dbt_semantic_interfaces/transformations/transform_rule.py
  dbt_semantic_interfaces/validations/element_const.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/non_empty.py
  dbt_semantic_interfaces/validations/reserved_keywords.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/fixtures/semantic_manifest_fixtures.py
  tests/transformations/test_configurable_transform_rules.py
  tests/validations/test_agg_time_dimension.py
  tests/validations/test_common_entities.py
  tests/validations/test_configurable_rules.py
  tests/validations/test_dimension_const.py
  tests/validations/test_element_const.py
  tests/validations/test_entities.py
  tests/validations/test_measures.py
  tests/validations/test_metrics.py
  tests/validations/test_unique_valid_name.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes, Skip Changelog
