Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-06, with the labels that each got.

#84 Assorted Fixes
  .github/pull_request_template.md
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/transformations/semantic_manifest_transformer.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/fixtures/semantic_manifest_fixtures.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_dataclass_serialization.py
  tests/validations/test_common_entities.py
  tests/validations/test_configurable_rules.py
  tests/validations/test_entities.py
  tests/validations/test_measures.py
  tests/validations/test_metrics.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes, Skip Changelog

#85 Add Validation for Semantic Model Defaults
  .changes/unreleased/Features-20230606-130140.yaml
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/validations/test_semantic_models.py
Labels: cla:yes

#87 Bump version to 0.1.0.dev5
  pyproject.toml
Labels: cla:yes, Skip Changelog

#89 Replace MetricType.EXPR with MetricType.DERIVED
  .changes/unreleased/Breaking Changes-20230615-152905.yaml
  dbt_semantic_interfaces/type_enums/metric_type.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/parsing/test_metric_parsing.py
  tests/validations/test_measures.py
Labels: cla:yes

#91 Update release to 0.1.0.dev6
  pyproject.toml
Labels: cla:yes, Skip Changelog

#90 Use Metrics Instead of Measures as Inputs to Ratio Metrics
  .changes/unreleased/Breaking Changes-20230615-153301.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/parsing/schemas/default_explicit_schema.json
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/parsing/test_metric_parsing.py
  tests/validations/test_dimension_const.py
  tests/validations/test_metrics.py
Labels: cla:yes

#92 Update release to 0.1.0.dev7
  pyproject.toml
Labels: cla:yes, Skip Changelog

#95 Add Configuration Object to Semantic Manifest
  .changes/unreleased/Features-20230623-114625.yaml
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_manifest.py
  dbt_semantic_interfaces/implementations/semantic_version.py
  dbt_semantic_interfaces/implementations/time_spine_table_configuration.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/parsing/explicit_schema.py
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/parsing/schemas/default_explicit_schema.json
  dbt_semantic_interfaces/protocols/project_configuration.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  dbt_semantic_interfaces/protocols/semantic_version.py
  dbt_semantic_interfaces/protocols/time_spine_configuration.py
  tests/example_project_configuration.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/project_configuration.yaml
  tests/implementations/test_semantic_manifest.py
  tests/parsing/test_metric_parsing.py
  tests/parsing/test_semantic_model_parsing.py
  tests/test_implements_satisfy_protocols.py
  tests/validations/test_dimension_const.py
  tests/validations/test_entities.py
  tests/validations/test_measures.py
  tests/validations/test_metrics.py
  tests/validations/test_semantic_models.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes

#96 Assorted Cleanup For schemas.py
  .github/workflows/ci-schema-consistency.yaml
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/parsing/generate_json_schema_file.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
Labels: cla:yes, Skip Changelog

#97 Increment Version to dev8
  pyproject.toml
Labels: cla:yes, Skip Changelog

#98 Remove debugging log line and increment package version
  dbt_semantic_interfaces/parsing/dir_to_model.py
  pyproject.toml
Labels: cla:yes, Skip Changelog

#100 Drop `create_metric` from the `Measure` protocol
  .changes/unreleased/Under the Hood-20230629-090156.yaml
  dbt_semantic_interfaces/protocols/measure.py
Labels: cla:yes, Protocol Spec Change

#101 Fix minor issues with semantic model defaults validation
  .changes/unreleased/Fixes-20230630-100007.yaml
  dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/validations/validator_helpers.py
Labels: cla:yes
