Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-07, with the labels that each got.

#113 Switch from `checked_agg_time_dimension` to `checked_agg_time_dimension_for_measure`
  .changes/unreleased/Breaking Changes-20230711-162541.yaml
  dbt_semantic_interfaces/implementations/elements/measure.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/protocols/measure.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/transformations/pydantic_rule_set.py
  dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/semantic_models.py
  tests/validations/test_agg_time_dimension.py
Labels: cla:yes, Protocol Spec Change

#114 Bump version to 0.1.0dev10
  pyproject.toml
Labels: cla:yes, Skip Changelog

#112 Relax Dependencies for Better Compatibility with Other Projects
  .changes/unreleased/Dependencies-20230711-141108.yaml
  dbt_semantic_interfaces/implementations/semantic_version.py
  pyproject.toml
Labels: cla:yes

#115 Repin ruff to `0.0.260`
  .changes/unreleased/Dependencies-20230712-141113.yaml
  pyproject.toml
Labels: cla:yes

#110 Add `call_parameter_sets` to the `WhereFilter` Protocol
  .changes/unreleased/Breaking Changes-20230711-131951.yaml
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  dbt_semantic_interfaces/parsing/where_filter_parser.py
  dbt_semantic_interfaces/protocols/where_filter.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#116 Bump version to `0.1.0rc1`
  pyproject.toml
Labels: cla:yes, Skip Changelog

#119 Fix `traceback.format_exception_only` calls for python 3.10+
  .changes/unreleased/Fixes-20230714-130338.yaml
  .github/workflows/ci-pytest.yaml
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  tests/validations/test_validator_helpers.py
Labels: bug, cla:yes

#122 Ensure `WhereFilterParser` uses a `SandboxedEnvironment` for jinja invocations
  .changes/unreleased/Under the Hood-20230720-104447.yaml
  dbt_semantic_interfaces/parsing/where_filter_parser.py
Labels: cla:yes

#126 Default `validate_semantic_manifest` to operate synchronously
  .changes/unreleased/Under the Hood-20230726-094145.yaml
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/validations/test_semantic_manifest_validator.py
Labels: cla:yes

#124 Add Primary Entity Field
  .changes/unreleased/Breaking Changes-20230724-135614.yaml
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/entity.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/validations/primary_entity.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/accounts_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/revenue.yaml
  tests/validations/test_entities.py
  tests/validations/test_metrics.py
  tests/validations/test_primary_entity.py
  tests/validations/test_validity_param_definitions.py
Labels: cla:yes

#127 Add `PrimaryEntityDimensionPairs` validation rule
  .changes/unreleased/Features-20230727-161128.yaml
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/user_sm_source.yaml
  tests/validations/test_metrics.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes, Validations

#131 Add `WhereFiltersAreParseable` Validation Rule
  .changes/unreleased/Features-20230728-090857.yaml
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  tests/validations/test_metrics.py
Labels: cla:yes, Validations

#128 Add Primary Entity Prefix When Specifying Dimensions in the WhereFilter
  .changes/unreleased/Breaking Changes-20230727-165005.yaml
  dbt_semantic_interfaces/naming/__init__.py
  dbt_semantic_interfaces/naming/dundered.py
  dbt_semantic_interfaces/naming/keywords.py
  dbt_semantic_interfaces/parsing/where_filter_parser.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#130 Use CamelCase in the `WhereFilter` Template Calls
  .changes/unreleased/Breaking Changes-20230727-170535.yaml
  dbt_semantic_interfaces/parsing/where_filter_parser.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes
