Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2023-09, with the labels that each got.

#150 Update valid name regex to disallow dunders
  .changes/unreleased/Fixes-20230914-134708.yaml
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/validations/test_unique_valid_name.py
Labels: bug, cla:yes

#151 [BACKPORT 0.2.latest] Disallow dunders in object names (#150)
  .changes/unreleased/Fixes-20230914-134708.yaml
  dbt_semantic_interfaces/validations/unique_valid_name.py
  tests/validations/test_unique_valid_name.py
Labels: cla:yes, Backport

#148 Add New SavedQuery Protocol
  .changes/unreleased/Features-20230913-172754.yaml
  .pre-commit-config.yaml
  dbt_semantic_interfaces/implementations/saved_query.py
  dbt_semantic_interfaces/implementations/semantic_manifest.py
  dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/protocols/saved_query.py
  dbt_semantic_interfaces/protocols/semantic_manifest.py
  dbt_semantic_interfaces/validations/primary_entity.py
  dbt_semantic_interfaces/validations/saved_query.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  pyproject.toml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/saved_queries.yaml
  tests/validations/test_entities.py
  tests/validations/test_saved_query.py
Labels: cla:yes

#152 Support for `Dimension.grain(...)` in where/filter
  .changes/unreleased/Features-20230918-112159.yaml
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_dimension.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_entity.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_parser.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  dbt_semantic_interfaces/parsing/where_filter_parser.py
  dbt_semantic_interfaces/protocols/query_interface.py
  dbt_semantic_interfaces/validations/saved_query.py
  tests/implementations/where_filter/test_parse_calls.py
Labels: cla:yes

#154 Support for descending & date_part in query interface
  .changes/unreleased/Under the Hood-20230921-161752.yaml
  dbt_semantic_interfaces/errors.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_dimension.py
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  dbt_semantic_interfaces/protocols/query_interface.py
Labels: cla:yes

#156 Fix TimeDimension parameter ordering
  .changes/unreleased/Fixes-20230926-092650.yaml
  dbt_semantic_interfaces/parsing/where_filter/where_filter_time_dimension.py
  dbt_semantic_interfaces/protocols/query_interface.py
Labels: cla:yes

#157 0.3.0a2 pre-release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#160 Migrated jsonschema.RefResolver to referencing.Registry
  .changes/unreleased/Dependencies-20230927-234903.yaml
  dbt_semantic_interfaces/parsing/schemas.py
  pyproject.toml
Labels: cla:yes

#159 Add null value coalescing options to `MetricInputMeasure` protocol
  .changes/unreleased/Features-20230926-182305.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/metric.py
  tests/parsing/test_metric_parsing.py
Labels: cla:yes, Protocol Spec Change, Backport 0.2.latest
