Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2024-07, with the labels that each got.

#299 Enable validations for cumulative type params
  dbt_semantic_interfaces/validations/metrics.py
  pyproject.toml
  tests/validations/test_metrics.py
Labels: cla:yes, Skip Changelog

#304 Set `default_granularity` properly for nested metrics
  dbt_semantic_interfaces/transformations/default_granularity.py
  pyproject.toml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/metrics.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_source.yaml
  tests/transformations/test_configurable_transform_rules.py
Labels: cla:yes, Skip Changelog

#305 Default granularity bug fix: handle time dimensions with the same name
  dbt_semantic_interfaces/transformations/default_granularity.py
  pyproject.toml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_monthly.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_source.yaml
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/semantic_models/bookings_yearly.yaml
Labels: cla:yes, Skip Changelog

#307 Don't require `time_granularity_name` in `QueryInterfaceTimeDimensionFactory`
  .changes/unreleased/Fixes-20240703-131327.yaml
  dbt_semantic_interfaces/protocols/query_interface.py
Labels: cla:yes

#308 Add full SL team to `CODEOWNERS`
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#309 Remove inconsistent Jinja param errors
  dbt_semantic_interfaces/call_parameter_sets.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  dbt_semantic_interfaces/type_enums/__init__.py
  pyproject.toml
  tests/implementations/where_filter/test_parse_calls.py
  tests/parsing/test_where_filter_parsing.py
Labels: cla:yes, Skip Changelog

#295 Make all `*Reference` classes orderable
  dbt_semantic_interfaces/references.py
Labels: cla:yes, Skip Changelog

#311 Remove `SetMetricTimeGranularityRule`
  dbt_semantic_interfaces/transformations/metric_time_granularity.py
  dbt_semantic_interfaces/transformations/pydantic_rule_set.py
  tests/transformations/test_configurable_transform_rules.py
Labels: Skip Changelog

#313 Only give one validation warning for deprecated cumulative fields
  dbt_semantic_interfaces/validations/metrics.py
  pyproject.toml
  tests/validations/test_metrics.py
Labels: cla:yes, Skip Changelog

#314 Add new time spine configuration
  .changes/unreleased/Features-20240716-104215.yaml
  dbt_semantic_interfaces/implementations/node_relation.py
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/implementations/time_spine.py
  dbt_semantic_interfaces/implementations/time_spine_table_configuration.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/node_relation.py
  dbt_semantic_interfaces/protocols/project_configuration.py
  dbt_semantic_interfaces/protocols/semantic_model.py
  dbt_semantic_interfaces/protocols/time_spine.py
  dbt_semantic_interfaces/protocols/time_spine_configuration.py
  dbt_semantic_interfaces/test_utils.py
  tests/example_project_configuration.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/project_configuration.yaml
  tests/validations/test_reserved_keywords.py
Labels: cla:yes

#315 Test serializability of `SerializableDataclass` subclasses
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/references.py
  dbt_semantic_interfaces/test_helpers/__init__.py
  dbt_semantic_interfaces/test_helpers/dataclass_serialization.py
  tests/serialization/__init__.py
  tests/serialization/test_serializable_dataclass_subclasses.py
Labels: cla:yes, Skip Changelog

#317 Remove name from time spine config
  dbt_semantic_interfaces/implementations/time_spine.py
  dbt_semantic_interfaces/parsing/generated_json_schemas/default_explicit_schema.json
  dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/protocols/time_spine.py
  tests/example_project_configuration.py
  tests/fixtures/semantic_manifest_yamls/simple_semantic_manifest/project_configuration.yaml
Labels: cla:yes, Skip Changelog

#319 Bump version
  pyproject.toml
Labels: cla:yes, Skip Changelog

#320 Add validations for time spines
  dbt_semantic_interfaces/protocols/__init__.py
  dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/validations/semantic_manifest_validator.py
  dbt_semantic_interfaces/validations/time_spines.py
  tests/validations/test_time_spines.py
Labels: cla:yes, Skip Changelog

#321 Bump version
  pyproject.toml
Labels: cla:yes, Skip Changelog
