Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2024-01, with the labels that each got.

#238 Begin supporting Pydantic 2 (without dropping support for Pydantic 1)
  .changes/unreleased/Dependencies-20231221-130418.yaml
  .github/workflows/ci-pre-commit.yaml
  .github/workflows/ci-pytest.yaml
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/implementations/base.py
  dbt_semantic_interfaces/implementations/export.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  pydantic_shim.py
  pyproject.toml
Labels: cla:yes, House keeping

#240 [BACKPORT] #238 to 0.4.latest (Pydantic 2 Support)
  .changes/unreleased/Dependencies-20231221-130418.yaml
  .github/workflows/ci-pre-commit.yaml
  .github/workflows/ci-pytest.yaml
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/implementations/base.py
  dbt_semantic_interfaces/implementations/export.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  pydantic_shim.py
  pyproject.toml
Labels: cla:yes

#243 Ensure wheel distribution includes pydantic shim
  .changes/unreleased/Under the Hood-20240104-120817.yaml
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/implementations/base.py
  dbt_semantic_interfaces/implementations/export.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  dsi_pydantic_shim.py
  pyproject.toml
Labels: cla:yes, Backport 0.4.latest

#244 [BACKPORT] #243 to 0.4.latest (wheel distribution fix)
  .changes/unreleased/Under the Hood-20240104-120817.yaml
  dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/implementations/base.py
  dbt_semantic_interfaces/implementations/export.py
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/implementations/project_configuration.py
  dbt_semantic_interfaces/implementations/semantic_model.py
  dbt_semantic_interfaces/validations/validator_helpers.py
  dsi_pydantic_shim.py
  pyproject.toml
Labels: cla:yes

#246 0.5.0a3 Release PR
  pyproject.toml
Labels: cla:yes, Skip Changelog, Rekease

#247 0.4.3 Release PR
  pyproject.toml
Labels: cla:yes, Skip Changelog, Rekease

#215 Add codeowners
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#245 Update pyproject.toml to show license on PyPI
  .changes/unreleased/Docs-20240108-193257.yaml
  pyproject.toml
Labels: cla:yes

#258 Fix: `Referencing entities in where filter causes an error.`
  .changes/unreleased/Fixes-20240129-110034.yaml
  dbt_semantic_interfaces/implementations/filters/where_filter.py
  dbt_semantic_interfaces/parsing/where_filter/parameter_set_factory.py
  tests/implementations/where_filter/test_parse_calls.py
  tests/parsing/test_where_filter_parsing.py
Labels: cla:yes, Backport 0.4.latest
