Repository dbt-labs/dbt-semantic-interfaces, pull requests merged in 2025-09, with the labels that each got.

#406 Remove non-working validation
  dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/validations/validator_helpers.py
Labels: Skip Changelog

#410 Remove individuals from CODEOWNERS
  .github/CODEOWNERS
Labels: cla:yes, Skip Changelog

#411 Bump version
  pyproject.toml
Labels: cla:yes, Skip Changelog

#413 Bump version to 0.9.2
  pyproject.toml
Labels: cla:yes, Skip Changelog

#414 Remove duplicate `expr` field
  .changes/unreleased/Under the Hood-20250910-131639.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/protocols/metric.py
  dbt_semantic_interfaces/validations/metrics.py
  tests/validations/metrics/test_conversion_metrics.py
  tests/validations/test_metrics.py
Labels: cla:yes

#415 Bump version and make it a dev version
  pyproject.toml
Labels: cla:yes, Skip Changelog

#416 Enhance test with a validation-passing case
  tests/validations/test_metrics.py
Labels: cla:yes, Skip Changelog

#417 Transform measures with create_metric true to actual metrics
  .changes/unreleased/Under the Hood-20250910-172813.yaml
  dbt_semantic_interfaces/implementations/metric.py
  dbt_semantic_interfaces/transformations/proxy_measure.py
  tests/transformations/test_proxy_measure_transformation_rule.py
Labels: cla:yes

#427 Remove measure requirement from AddInputMetricMeasuresRule
  dbt_semantic_interfaces/transformations/add_input_metric_measures.py
Labels: cla:yes, Skip Changelog

#428 Add test for existing boolean aggregation transformation
  tests/transformations/test_boolean_measure_aggregation_rule.py
Labels: cla:yes, Skip Changelog

#430 Add tests for existing convert count rule
  tests/transformations/test_convert_count_rule.py
Labels: cla:yes, Skip Changelog

#432 Add tests for convert median transformation for measures
  dbt_semantic_interfaces/transformations/convert_median.py
  tests/transformations/test_convert_median_rule.py
Labels: cla:yes, Skip Changelog
